Destroy infra

diff --git a/.github/workflows/infra-deploy.yml b/.github/workflows/infra-deploy.yml
--- a/.github/workflows/infra-deploy.yml
+++ b/.github/workflows/infra-deploy.yml
@@ -2,11 +2,11 @@
 name: Infra Deploy
 
 on:
-  # # push:
-  # #   branches:
-  # #     - main
-  #   paths:
-  #     - terraform/**
+  push:
+    branches:
+      - main
+    paths:
+      - terraform/**
     
   workflow_dispatch: 
 
@@ -19,53 +19,53 @@ env:
   S3_BUCKET: ${{ vars.S3_BUCKET }}
 
 jobs:
-  terraform:
-    name: Terraform Apply
-    runs-on: ubuntu-latest
+  # terraform:
+  #   name: Terraform Apply
+  #   runs-on: ubuntu-latest
 
-     # Run only on push eventss
-    if: github.event_name == 'push'
+  #    # Run only on push eventss
+  #   if: github.event_name == 'push'
 
-    defaults:
-      run:
-        shell: bash
-        working-directory: ./terraform
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #       working-directory: ./terraform
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ env.AWS_REGION }}
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
 
-      - name: Terraform Init
-        run: terraform init -backend-config="bucket=${{ env.S3_BUCKET }}"
+  #     - name: Terraform Init
+  #       run: terraform init -backend-config="bucket=${{ env.S3_BUCKET }}"
 
-      - name: Terraform validate
-        run: terraform validate
+  #     - name: Terraform validate
+  #       run: terraform validate
 
-      - name: Terraform Plan
-        run: terraform plan -no-color -input=false -out plainfile
+  #     - name: Terraform Plan
+  #       run: terraform plan -no-color -input=false -out plainfile
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+  #     - name: Terraform Plan Status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
 
-      - name: Terraform Apply
-        run: terraform apply -auto-approve -input=false -parallelism=1 plainfile
+  #     - name: Terraform Apply
+  #       run: terraform apply -auto-approve -input=false -parallelism=1 plainfile
 
-      - name: EKS Update Kubeconfig
-        id: getEksConfig
-        if: steps.apply.outcome == 'success'
-        run: |
-          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
+  #     - name: EKS Update Kubeconfig
+  #       id: getEksConfig
+  #       if: steps.apply.outcome == 'success'
+  #       run: |
+  #         aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
 
       # - name: Install Ingress Nginx Controller
       #   if: steps.apply.outcome == 'success' && steps.getEksConfig.outcome == 'success'
